spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/dojo_liquibase?useSSL=false
    username: root
    password: 123456

liquibase:
  enabled: false
  change-log: classpath:/database/db.changelog-master.yml